### ISSUE TITLE
Translation of old CVS repo to git

### ISSUE THREAD

**Issue by rdebath** [mzattera/bfbasic#1]
I just noticed what you've been doing and thought you might like to put it on top of the original repository.

The translated repository is at: https://github.com/rdebath/bfbasic
The master branch is `BFBasic` and there's a second branch for `c2bf`.

**Comment by mzattera** [comment]
Hi! Thanks a lot for he suggestion. I added a link to your repo in my readme file, so people landing here will be aware of your project as well (which I was not able to find then when googling, it would have saved me some time :)).

However, I see that, while I moved to Eclipse and reworked the file structure, you kept the original setup; this makes it a bit difficult for me to understand what you mean.

Should I add a new folder (1.50 rc3) and copy there contents form  [my source folder](https://github.com/mzattera/bfbasic/tree/master/bfbasic/src)? I see you have a "src" foder with 1.50 rc2, maybe rename that and make a new folder "src" folder instead?

Could you please advise?

Thanks
Maxi

**Comment by rdebath** [comment]
Well, I was thinking something like this https://github.com/rdebath/bfbasic/commits/master

I've shuffled the files around on the 1st of July and then attached most of your commits to the end.
Unfortunately it doesn't look like `git-blame` can work because you've reformatted the files.

**Comment by mzattera** [comment]
Hi Apologies for the late reply. I am a very basic user when it comes to github so I was not aware of this possibility. However, it seems you fixed it, so I will close this issue. If ther eis anything else needed on my side,please let me know.

**Comment by mzattera** [comment]
See last comment
